matrix:
  include:
    - dist: xenial
      language: python
      python:
        - "3.7"

      install:
        - pip install -r requirements.txt

      script:
        - make isort
        - make black
        - cd src/backend
        - python manage.py test

    - language: node_js
      node_js:
        - "stable"
      cache:
        directories:
          - "node_modules"
      script:
        - npm test
