coverage:
	range: "90..100"
	round: nearest
	precision: 2
	status:
		patch:
			default:
				target: 90%
				threshold: null
		project:
			default:
				target: 90%
				threshold: null

comment:
	layout: "reach, diff, flags, files"

ignore:
	- src/server/manage.py
	- src/server/portfolio/settings.py